
const PAGE_CHUNK=48; let __idx=[],__loaded=new Set(),__buf=[],__off=0,__filtered=[];
async function j(u){ const r=await fetch(u); if(!r.ok) throw new Error('HTTP '+r.status+' '+u); return r.json(); }
async function loadIndex(){ if(__idx.length) return __idx; try{ const i=await j('data/pages/index.json'); __idx=i; return i; }catch(e){ const el=document.querySelector('#grid'); if(el) el.innerHTML='<div class="alert">تعذّر تحميل فهرس الداتا. شغّل سيرفر محلي.</div>'; return []; } }
async function loadPage(p){ if(__loaded.has(p)) return; const a=await j('data/pages/'+p); __buf=__buf.concat(a); __loaded.add(p); }
function q(k){ return new URLSearchParams(location.search).get(k); }
function star(r){ return '⭐'.repeat(Math.round(r)); }
function priceBlock(p){ const cur=Currency.current(); const val=convertPrice(p.price,cur); return `<span class='price'>${fmtMoney(val,cur)}</span> <span class='muted'>(~${fmtMoney(p.price,'USD')})</span>`; }
function card(p){ const d=document.createElement('div'); d.className='card'; d.innerHTML=`<img src='${p.image}' alt='${p.name}'><div class='info'><div class='title'>${p.name}</div><div class='muted'>${p.brand} • ${p.category} • ${p.source} • ${star(p.rating)} (${p.reviewsCount})</div>${priceBlock(p)}<div class='muted'>${p.short||''}</div></div><div class='actions'><a class='button' href='product.html?id=${p.id}'>تفاصيل</a><a class='button secondary' href='${affiliateUrl(p)}' target='_blank' rel='noopener'>شراء من المصدر</a></div>`; return d; }
function applyFilters(list){ let f=list; const _q=q('q'),cat=q('category'),brand=q('brand'),src=q('source'),min=parseFloat(q('min')),max=parseFloat(q('max')); if(cat) f=f.filter(p=>p.category===cat); if(brand) f=f.filter(p=>p.brand===brand); if(src) f=f.filter(p=>p.source===src); if(!Number.isNaN(min)) f=f.filter(p=>p.price>=min); if(!Number.isNaN(max)) f=f.filter(p=>p.price<=max); if(_q){ const qq=_q.toLowerCase(); f=f.filter(p=>(p.name+' '+(p.description||'')+' '+(p.brand||'')).toLowerCase().includes(qq)); } return f; }
function renderMore(el){ const s=__filtered.slice(__off,__off+PAGE_CHUNK); s.forEach(p=>el.appendChild(card(p))); __off+=s.length; }
function onScroll(el){ let t=false; addEventListener('scroll', async()=>{ if(t) return; t=true; requestAnimationFrame(async()=>{ const near=(innerHeight+scrollY)>(document.body.offsetHeight-360); if(near){ if(__off<__filtered.length){ renderMore(el); } else { const nxt=__idx.find(p=>!__loaded.has(p)); if(nxt){ await loadPage(nxt); __filtered=applyFilters(__buf); renderMore(el); } } } t=false; }); }); }
async function renderGrid(sel){ const el=document.querySelector(sel); if(!el) return; __buf=[]; __loaded=new Set(); __off=0; const pages=await loadIndex(); if(!pages.length) return; for(const p of pages.slice(0,2)){ await loadPage(p); } __filtered=applyFilters(__buf); el.innerHTML=''; renderMore(el); onScroll(el); if(!__filtered.length){ el.innerHTML='<div class="alert">لا نتائج — غيّر الفلاتر أو البحث.</div>'; } }
async function renderProduct(){ const box=document.querySelector('#product'); if(!box) return; const id=q('id'); let page=null; try{ const map=await j('data/pages/lookup.json'); page=map[id]; }catch(e){}
  let p=null; if(page){ try{ const a=await j('data/pages/'+page); p=a.find(x=>x.id===id); }catch(e){} }
  if(!p){ box.innerHTML='<div class="alert">المنتج غير موجود.</div>'; return; }
  const cur=Currency.current(), priceCur=fmtMoney(convertPrice(p.price,cur),cur), priceUsd=fmtMoney(p.price,'USD');
  box.innerHTML=`<div class='breadcrumbs'><a href='index.html'>الرئيسية</a> / <a href='products.html?category=${encodeURIComponent(p.category)}'>${p.category}</a> / ${p.name}</div><div class='main-hero'><img src='${p.image}' alt='${p.name}' style='width:48%; border-radius:12px; max-width:520px;'><div style='flex:1'><h1>${p.name}</h1><p class='muted'>${p.brand} • ${p.category} • ${p.source} • ${star(p.rating)} (${p.reviewsCount})</p><p class='price'>${priceCur} <span class='muted'>(~${priceUsd})</span></p><p>${p.description||''}</p><div class='filters' style='margin-top:12px'>${(p.features||[]).map(x=>`<span class='badge'>${x}</span>`).join(' ')}</div><div style='display:flex; gap:8px; margin-top:14px;'><a class='button' href='${affiliateUrl(p)}' target='_blank' rel='noopener'>شراء من المصدر</a><a class='button secondary' href='products.html?brand=${encodeURIComponent(p.brand)}'>المزيد من ${p.brand}</a></div></div></div>`;
  const ld={"@context":"https://schema.org/","@type":"Product",name:p.name,brand:p.brand,category:p.category,image:p.image,description:p.description,offers:{"@type":"Offer",price:p.price,priceCurrency:'USD',availability:"https://schema.org/InStock",url:affiliateUrl(p)},aggregateRating:{"@type":"AggregateRating",ratingValue:p.rating,reviewCount:p.reviewsCount}}; const s=document.createElement('script'); s.type='application/ld+json'; s.textContent=JSON.stringify(ld); document.head.appendChild(s);
}
function initSearch(){ const i=document.querySelector('#search-input'); const b=document.querySelector('#search-btn'); if(i&&b) b.addEventListener('click',()=>{ const u=new URL('products.html',location.href); if(i.value.trim()) u.searchParams.set('q', i.value.trim()); location.href=u.toString(); }); }
function initCurrency(){ const sel=document.querySelector('#currency'); if(!sel) return; sel.value=Currency.current(); sel.addEventListener('change',()=>Currency.set(sel.value)); }
addEventListener('DOMContentLoaded',()=>{ renderGrid('#grid'); renderProduct(); initSearch(); initCurrency(); });
